#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "0b924d0bb4634ec2ac47981fb58e5832" }
]

[assets]
directory = "./public"
